/*
Seed script for products.
Run with:
  node -r dotenv/config scripts/seedProducts.js
This will load .env from project root for `MONGODB_URI`.
*/

let db = require('../utils/db');
db = db.default || db;
let Product = require('../models/Product');
Product = Product.default || Product;

async function seed() {
  try {
    await db.connect();

    const sampleProducts = [
      {
        name: 'Acme Running Shoes',
        slug: 'acme-running-shoes',
        category: 'Shoes',
        image: '/images/shoes1.jpg',
        price: 79.99,
        brand: 'Acme',
        rating: 4.5,
        ratings: [50, 10, 5, 2, 1],
        totalRatings: 68,
        numReviews: 12,
        reviews: ['Comfortable and light', 'Good value for money'],
        countInStock: 25,
        description: 'Lightweight running shoes with breathable fabric and cushioned sole.',
        isFeatured: true,
        banner: '/banners/shoes1-banner.jpg',
      },
      {
        name: 'Zenith Smartphone X12',
        slug: 'zenith-smartphone-x12',
        category: 'Electronics',
        image: '/images/phone1.jpg',
        price: 599.0,
        brand: 'Zenith',
        rating: 4.7,
        ratings: [120, 30, 10, 5, 2],
        totalRatings: 167,
        numReviews: 45,
        reviews: ['Excellent camera', 'Battery lasts long'],
        countInStock: 40,
        description: 'Flagship smartphone with 6.7-inch display, 128GB storage, and triple camera.',
        isFeatured: true,
        banner: '/banners/phone1-banner.jpg',
      },
      {
        name: 'HomeBlend Coffee Maker',
        slug: 'homeblend-coffee-maker',
        category: 'Home Appliances',
        image: '/images/coffee1.jpg',
        price: 129.99,
        brand: 'HomeBlend',
        rating: 4.2,
        ratings: [30, 12, 8, 4, 1],
        totalRatings: 55,
        numReviews: 20,
        reviews: ['Makes great coffee', 'Easy to clean'],
        countInStock: 15,
        description: 'Programmable coffee maker with 12-cup capacity and auto-shutoff feature.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'Aurora Desk Lamp',
        slug: 'aurora-desk-lamp',
        category: 'Furniture',
        image: '/images/lamp1.jpg',
        price: 39.99,
        brand: 'Aurora',
        rating: 4.0,
        ratings: [10, 5, 2, 1, 0],
        totalRatings: 18,
        numReviews: 4,
        reviews: ['Bright and adjustable'],
        countInStock: 50,
        description: 'LED desk lamp with adjustable brightness and flexible neck.',
        isFeatured: false,
        banner: '/banners/lamp1-banner.jpg',
      },
      {
        name: 'ProCook Chef Knife',
        slug: 'procook-chef-knife',
        category: 'Kitchen',
        image: '/images/knife1.jpg',
        price: 24.5,
        brand: 'ProCook',
        rating: 4.6,
        ratings: [80, 10, 3, 1, 0],
        totalRatings: 94,
        numReviews: 25,
        reviews: ['Sharp and balanced'],
        countInStock: 100,
        description: '8-inch stainless steel chef knife with ergonomic handle.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'Studio Wireless Headphones',
        slug: 'studio-wireless-headphones',
        category: 'Audio',
        image: '/images/headphones1.jpg',
        price: 149.99,
        brand: 'Studio',
        rating: 4.4,
        ratings: [70, 20, 8, 3, 1],
        totalRatings: 102,
        numReviews: 33,
        reviews: ['Great sound quality', 'Comfortable for long use'],
        countInStock: 30,
        description: 'Over-ear wireless headphones with active noise cancellation and 30h battery.',
        isFeatured: true,
        banner: '/banners/headphones1-banner.jpg',
      },
      {
        name: 'Nebula Smartwatch Z',
        slug: 'nebula-smartwatch-z',
        category: 'Wearables',
        image: '/images/watch1.jpg',
        price: 199.0,
        brand: 'Nebula',
        rating: 4.3,
        ratings: [40, 15, 5, 2, 0],
        totalRatings: 62,
        numReviews: 14,
        reviews: ['Lightweight and accurate', 'Good battery life'],
        countInStock: 45,
        description: 'Smartwatch with heart-rate monitor, GPS, and 7-day battery life.',
        isFeatured: false,
        banner: '/banners/watch1-banner.jpg',
      },
      {
        name: 'RidgeTrail Backpack 30L',
        slug: 'ridgetrail-backpack-30l',
        category: 'Outdoors',
        image: '/images/backpack1.jpg',
        price: 89.99,
        brand: 'RidgeTrail',
        rating: 4.5,
        ratings: [60, 12, 4, 2, 0],
        totalRatings: 78,
        numReviews: 22,
        reviews: ['Durable and roomy'],
        countInStock: 60,
        description: 'Water-resistant 30L backpack with padded laptop sleeve and ergonomic straps.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'BlendMaster Pro Blender',
        slug: 'blendmaster-pro-blender',
        category: 'Kitchen',
        image: '/images/blender1.jpg',
        price: 219.5,
        brand: 'BlendMaster',
        rating: 4.1,
        ratings: [20, 8, 5, 3, 1],
        totalRatings: 37,
        numReviews: 9,
        reviews: ['Powerful motor, great smoothies'],
        countInStock: 12,
        description: 'High-power blender with multiple speed settings and a durable pitcher.',
        isFeatured: false,
        banner: '/banners/blender1-banner.jpg',
      },
      {
        name: 'EcoYoga Mat',
        slug: 'ecoyoga-mat',
        category: 'Fitness',
        image: '/images/yogamat1.jpg',
        price: 29.99,
        brand: 'EcoFit',
        rating: 4.0,
        ratings: [15, 6, 2, 1, 0],
        totalRatings: 24,
        numReviews: 6,
        reviews: ['Non-slip and comfortable'],
        countInStock: 80,
        description: 'Eco-friendly non-slip yoga mat made from natural materials.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'TinyTots Building Set',
        slug: 'tinytots-building-set',
        category: 'Toys',
        image: '/images/toy1.jpg',
        price: 34.99,
        brand: 'TinyTots',
        rating: 4.8,
        ratings: [90, 10, 1, 0, 0],
        totalRatings: 101,
        numReviews: 40,
        reviews: ['Great for kids learning shapes'],
        countInStock: 150,
        description: 'Colorful building blocks set for children aged 3 and up.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'GamerPro Wired Mouse',
        slug: 'gamerpro-wired-mouse',
        category: 'Gaming',
        image: '/images/mouse1.jpg',
        price: 49.99,
        brand: 'GamerPro',
        rating: 4.6,
        ratings: [70, 8, 3, 1, 0],
        totalRatings: 82,
        numReviews: 20,
        reviews: ['Responsive and comfortable'],
        countInStock: 55,
        description: 'Wired gaming mouse with adjustable DPI and programmable buttons.',
        isFeatured: false,
        banner: '/banners/mouse1-banner.jpg',
      },
      {
        name: 'CrystalView 27 Monitor',
        slug: 'crystalview-27-monitor',
        category: 'Electronics',
        image: '/images/monitor1.jpg',
        price: 279.99,
        brand: 'CrystalView',
        rating: 4.2,
        ratings: [25, 10, 4, 2, 1],
        totalRatings: 42,
        numReviews: 11,
        reviews: ['Crisp colors and thin bezels'],
        countInStock: 20,
        description: '27-inch 1440p monitor with IPS panel and 75Hz refresh rate.',
        isFeatured: false,
        banner: '/banners/monitor1-banner.jpg',
      },
      {
        name: 'StormGuard Rain Jacket',
        slug: 'stormguard-rain-jacket',
        category: 'Apparel',
        image: '/images/jacket1.jpg',
        price: 119.0,
        brand: 'StormGuard',
        rating: 4.3,
        ratings: [30, 9, 2, 1, 0],
        totalRatings: 42,
        numReviews: 10,
        reviews: ['Lightweight and waterproof'],
        countInStock: 35,
        description: 'Packable waterproof jacket with breathable membrane.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'Solstice Sunglasses',
        slug: 'solstice-sunglasses',
        category: 'Accessories',
        image: '/images/sunglasses1.jpg',
        price: 59.99,
        brand: 'Solstice',
        rating: 4.0,
        ratings: [12, 6, 3, 1, 0],
        totalRatings: 22,
        numReviews: 5,
        reviews: ['Stylish and UV-protective'],
        countInStock: 70,
        description: 'Polarized sunglasses with lightweight frame.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'Aurora Hardcover Novel',
        slug: 'aurora-hardcover-novel',
        category: 'Books',
        image: '/images/book1.jpg',
        price: 18.99,
        brand: 'Aurora Press',
        rating: 4.7,
        ratings: [40, 6, 2, 0, 0],
        totalRatings: 48,
        numReviews: 16,
        reviews: ['Gripping story and well-written'],
        countInStock: 120,
        description: 'A bestselling novel with thrilling plot twists and memorable characters.',
        isFeatured: false,
        banner: '',
      },
      {
        name: 'Vortex Bagless Vacuum',
        slug: 'vortex-bagless-vacuum',
        category: 'Home Appliances',
        image: '/images/vacuum1.jpg',
        price: 199.99,
        brand: 'Vortex',
        rating: 4.1,
        ratings: [18, 7, 3, 2, 1],
        totalRatings: 31,
        numReviews: 8,
        reviews: ['Strong suction and easy to empty'],
        countInStock: 22,
        description: 'Bagless upright vacuum with HEPA filtration and multiple attachments.',
        isFeatured: false,
        banner: '/banners/vacuum1-banner.jpg',
      },
      {
        name: 'DreamSleep Mattress (Queen)',
        slug: 'dreamsleep-mattress-queen',
        category: 'Home',
        image: '/images/mattress1.jpg',
        price: 799.0,
        brand: 'DreamSleep',
        rating: 4.5,
        ratings: [55, 10, 5, 1, 0],
        totalRatings: 71,
        numReviews: 27,
        reviews: ['Comfortable and supportive'],
        countInStock: 10,
        description: 'Medium-firm hybrid mattress with memory foam layer and pocketed coils.',
        isFeatured: true,
        banner: '/banners/mattress1-banner.jpg',
      },
    ];

    // Optionally clear existing products - comment out if you want to keep existing
    // await Product.deleteMany({});

    for (const p of sampleProducts) {
      const exists = await Product.findOne({ slug: p.slug });
      if (!exists) {
        const product = new Product(p);
        await product.save();
        console.log('Inserted:', p.slug);
      } else {
        console.log('Already exists, skipped:', p.slug);
      }
    }

    await db.disconnect();
    console.log('Seeding completed');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    try {
      await db.disconnect();
    } catch (e) {}
    process.exit(1);
  }
}

seed();
